# Generated by Django 3.1.5 on 2021-01-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_branch_storeincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='heightdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('old', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('boy', models.CharField(max_length=200)),
                ('girl', models.CharField(max_length=200)),
            ],
        ),
    ]
